apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  #labels for development resources
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: devsecopswithaws/app1:0.0.1
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector: # labels are used as selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80